# nome da pipeline
name: Run Basic Tests Azure

# Em que momento será executada
on:
  pull_request:
    branches: [main]

jobs:
  # O que vai ser feito nessa pipeline
  # Só teremos um job: rodar os testes. Poderia ser qualquer nome no lugar do cypress-run abaixo
  cypress-run:
    # máquina que será executado
    runs-on: ubuntu-latest

    # Passo a passo para rodar os testes
    steps:
      # Clone do projeto
      - name: Checkout/Clone do projeto
        uses: actions/checkout@v3

      # Exemplos de execução no terminal
      - name: Instalar node
        run: npm install

      # Execução e configuração do projeto
      - name: Run tests
        uses: cypress-io/github-action@v5
        with:
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      
      # Upload do relatório do mocha
      - name: Upload relatório
        uses: actions/upload-artifact@v3
        with:
          name: Relatório
          path: cypress/reports/html